// Code generated by goctl. DO NOT EDIT.
package types

type AvatarInfo struct {
	UserId string `json:"userId"`
	Path   string `json:"path"`
}

type BaseMsgResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type IdReq struct {
	Id string `json:"id"`
}

type UserInfo struct {
	Username    *string `json:"username,optional"`
	Password    *string `json:"password,optional"`
	LoginStatus *uint64 `json:"loginStatus,optional"`
	Avatar      *string `json:"avatar,optional"`
	Email       *string `json:"email,optional"`
	Phone       *string `json:"phone,optional"`
}

type UserListReq struct {
	Page     uint64 `json:"page"`
	PageSize uint64 `json:"pageSize"`
}

type UserListResp struct {
	Total uint64     `json:"total"`
	Data  []UserInfo `json:"data"`
}

type UsernameReq struct {
	Username string `json:"username"`
}
