// Code generated by ent, DO NOT EDIT.

package ent

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilUsername(value *string) *UserUpdate {
	if value != nil {
		return u.SetUsername(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilUsername(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetUsername(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilUsername(value *string) *UserCreate {
	if value != nil {
		return u.SetUsername(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilPhone(value *string) *UserUpdate {
	if value != nil {
		return u.SetPhone(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilPhone(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetPhone(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilPhone(value *string) *UserCreate {
	if value != nil {
		return u.SetPhone(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilEmail(value *string) *UserUpdate {
	if value != nil {
		return u.SetEmail(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilEmail(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetEmail(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilEmail(value *string) *UserCreate {
	if value != nil {
		return u.SetEmail(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdate) SetNotNilAvatar(value *string) *UserUpdate {
	if value != nil {
		return u.SetAvatar(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserUpdateOne) SetNotNilAvatar(value *string) *UserUpdateOne {
	if value != nil {
		return u.SetAvatar(*value)
	}
	return u
}

// set field if value's pointer is not nil.
func (u *UserCreate) SetNotNilAvatar(value *string) *UserCreate {
	if value != nil {
		return u.SetAvatar(*value)
	}
	return u
}
