// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SysStudentColumns holds the columns for the "sys_student" table.
	SysStudentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true, Comment: "用户名"},
		{Name: "phone", Type: field.TypeString, Unique: true, Comment: "电话号码"},
		{Name: "email", Type: field.TypeString, Unique: true, Comment: "邮箱"},
		{Name: "avatar", Type: field.TypeString, Nullable: true, Comment: "头像路径", Default: "", SchemaType: map[string]string{"mysql": "varchar(512)"}},
	}
	// SysStudentTable holds the schema information for the "sys_student" table.
	SysStudentTable = &schema.Table{
		Name:       "sys_student",
		Columns:    SysStudentColumns,
		PrimaryKey: []*schema.Column{SysStudentColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_username",
				Unique:  true,
				Columns: []*schema.Column{SysStudentColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SysStudentTable,
	}
)

func init() {
	SysStudentTable.Annotation = &entsql.Annotation{
		Table: "sys_student",
	}
}
